### PR TITLE
add README, re PAN-2906

### PR DESCRIPTION
**Pull request by lazaridiscom**
Add an index-file (README) to the `development` folder, see PAN-2906.

(Dev related documents should be moved herein, and indexed in the README)

### CODE REVIEW

**Comment by lazaridiscom** [comment]
test: [PAN-2906]

**Comment by lazaridiscom** [comment]
> Merge the latest changes from master into this branch

not necessary

**Comment by lucassaldanha** [comment]
Thanks for your PR!

We already have a section in our README with all the links relevant to developing with Pantheon. There is no need for another section here.

https://github.com/PegaSysEng/pantheon/blob/master/README.md#pantheon-developers

Cheers!

**Comment by lazaridiscom** [comment]
@lucassaldanha , the best way to discourage contributions is to close issues very fast, without even understanding the whole context.

The main issue is: https://pegasys1.atlassian.net/browse/PAN-2906

I mentioned the main README and the necessary corrections there.

See, because the effort to create PR's is quite high, I did not applied all the steps.

**Pull request closed without merging**
