### PR TITLE
AT- Removing unused methods on KeyValueStorage

### PR DESCRIPTION
**Pull request by CjHare**
These methods are unused.
Applying the principle of YANGI and in preparation for supporting the plugin system for storage, this PR delete them.

### CODE REVIEW

**Comment by CjHare** [comment]
This is a duplicate of #1659 with the exception that the submodule for the reference tests is correct

**Comment by RatanRSur** [comment]
I need `containsKey` and `clear` but I think you're good to go to remove Entry

**Comment by CjHare** [comment]
@RatanRSur I've added back `containsKey` and `clear` ...for fun I ordered the methods alphabetically.

The only 'real' change now is removing the unused `EntryKey` from `KeyValueStorage`

**Comment by CjHare** [comment]
👍

**Pull request merged**
